// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./components/BottomSheet.vue')['default']
    BottomSheetHelper: typeof import('./components/BottomSheetHelper.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Content: typeof import('./components/Content.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgCircularProgress: typeof import('./components/SvgCircularProgress.vue')['default']
    SvgNumber: typeof import('./components/SvgNumber.vue')['default']
    SvgNumberPath: typeof import('./components/SvgNumberPath.vue')['default']
  }
}
