// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '(WIP': bottom sheet component)
    BottomSheet: typeof import('./components/BottomSheet.vue')['default']
    BottomSheetHelper: typeof import('./components/BottomSheetHelper.vue')['default']
    BottomSheetRewrite: typeof import('./components/BottomSheetRewrite.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    MaplibreMap: typeof import('./components/MaplibreMap.vue')['default']
    MapTest: typeof import('./components/MapTest.vue')['default']
    MglMap: typeof import('./components/MapTest.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleMap: typeof import('./components/SimpleMap.vue')['default']
    SvgNumber: typeof import('./components/SvgNumber.vue')['default']
    SvgNumberPath: typeof import('./components/SvgNumberPath.vue')['default']
  }
}
